### ISSUE TITLE
image not found

### ISSUE THREAD

**Issue by zacmontague** [tf-encrypted/tf-big#60]
Hi,

I am attempting to use this library. I receive the following error:

`>>> import tf_big
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zach/miniconda3/lib/python3.7/site-packages/tf_big/__init__.py", line 3, in <module>
    from tf_big.python.ops.big_ops import big_import
  File "/Users/zach/miniconda3/lib/python3.7/site-packages/tf_big/python/ops/big_ops.py", line 5, in <module>
    big_ops = load_library.load_op_library(op_lib_file)
  File "/Users/zach/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/Users/zach/miniconda3/lib/python3.7/site-packages/tf_big/python/ops/_big_ops.so, 6): Library not loaded: @rpath/libtensorflow_framework.so
  Referenced from: /Users/zach/miniconda3/lib/python3.7/site-packages/tf_big/python/ops/_big_ops.so
  Reason: image not found`

Right before I tried using tf_big, I switched over to miniconda for a clean install of python since my projects will use tensorflow from now on, and I want to take full advantage of the speed through conda's installation.

What do I need to do?

Thanks,
Zach

**Comment by justin1121** [comment]
Hey @zacmontague, did you install with `pip`? What version of tensorflow as you using?

**Comment by zacmontague** [comment]
Hi,

I switched from python 3.7.4 to python 3.6.9. I installed tf-big with pip and tensorflow with conda. I'm using tensorflow version 1.15.0. In particular, I've been using an environment that is built by running this script https://github.com/matsengrp/vampire/blob/master/install/environment.yml. 

I now get the following error. I've tried installing on both macOS and linux and run into the same error.

`>>> import tf_big
Could not load version specific .so file for '_big_ops', trying version neutral .so file
Could not load .so file
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zach/miniconda3/envs/vampire/lib/python3.6/site-packages/tf_big/__init__.py", line 1, in <module>
    from tf_big.python.tensor import set_secure_default
  File "/Users/zach/miniconda3/envs/vampire/lib/python3.6/site-packages/tf_big/python/tensor.py", line 4, in <module>
    import tf_big.python.ops.big_ops as ops
  File "/Users/zach/miniconda3/envs/vampire/lib/python3.6/site-packages/tf_big/python/ops/big_ops.py", line 45, in <module>
    big_import = big_ops.big_import
AttributeError: 'NoneType' object has no attribute 'big_import'`

**Comment by justin1121** [comment]
The pip package is only built to support tensorflow 1.13.1. I'd suggest trying to use that if possible or building from source. https://github.com/tf-encrypted/tf-big#development

**Comment by zacmontague** [comment]
Thank you! That solved it!
